### ISSUE TITLE
Northern San d'Oria Madaline and Telmoda onTrigger crash

### ISSUE THREAD

**Issue by ffxisf** [project-topaz/topaz#1055]
**_I have:_**

- [] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

**Comment by zach2good** [comment]
Welcome to Project Topaz! I'm going to post instructions on how to fix this issue (if you need to apply a hot-fix to your local server), and tag this so that someone else might be able to come along and fix this in our repo, thanks for reporting!

https://github.com/project-topaz/topaz/blob/release/scripts/zones/Northern_San_dOria/npcs/Madaline.lua#L13
https://github.com/project-topaz/topaz/blob/release/scripts/zones/Northern_San_dOria/npcs/Telmoda.lua#L14

These are in the form:
```lua
player:setCharVar(player, "Telmoda_Madaline_Event", 1)
```

but should be:
```lua
player:setCharVar("Telmoda_Madaline_Event", 1)
```

I imagine these will trigger a `TPZ_DEBUG_BREAK` when they hit core and the server will die :(

**Comment by zach2good** [comment]
Fixed in `release` with https://github.com/project-topaz/topaz/pull/1056, will get merged into `canary` in a few days. Thanks for reporting @ffxisf  👍
