### ISSUE TITLE
dps account date to tpz

### ISSUE THREAD

**Issue by siguma-zero** [project-topaz/topaz#555]
**_I have:_**

- [] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

hello~
Nice to meet you. I don't know much about the program. I want to know how to move dps data to tpz. Thanks in advance

**Comment by Kreidos** [comment]
Hi @siguma-zero, welcome!

Sadly, I believe your issue here will be closed as this isn't the place to seek support. Issue trackers are for reporting bugs or incorrect behaviour of the program and not for help requests. I recommend you engage with the friendly and helpful project members and users on [the Discord](https://discord.gg/nbYJfA5) in order to seek assistance. 

If, in your time with Topaz you encounter issues which are the direct result of a bug, I know it would be appreciated if you reported them here.

**Comment by ghost** [comment]
Hello, siguma-zero! Thank you, Kreidos, you explained it great. I think I can close this issue now, it's been 8 days. Thanks and see you on Discord!
